### PR TITLE
A clean solution to "allow setting additional data for OpenID model" (issue #30)

### PR DESCRIPTION
**Pull request by dmyersturnbull**
I added an extra `data` field that contains all of the returned JSON values. I think this is probably the cleanest solution. Let me know if you want any edits.

- feat: allow setting additional data for OpenID model
- docs: add data field

### CODE REVIEW

**Comment by akimrx** [comment]
In my opinion, this is not the best solution, which actually duplicates in most cases all the same fields. This PR actually just inject all the content from the HTTP response into additional attribute.

I think that for cases where custom fields are needed, it is more relevant to implement a flag like `serialize: bool = True` for the [verify_and_process](https://github.com/tomasvotava/fastapi-sso/blob/master/fastapi_sso/sso/base.py#L299C15-L299C33) method, which will then be injected to the [process_login](https://github.com/tomasvotava/fastapi-sso/blob/master/fastapi_sso/sso/base.py#L366C15-L366C28) method. 

A value of `False` would return a raw response. Without serialization to the OpenID model. By default is set to `True` so that the OpenID model is returned.

This will allow you to manage the response at the base class level in a single way for all implementations and maintain flexibility without affecting concrete implementations

**Comment by tomasvotava** [comment]
I have to say I am not a fan of having return type differ based on an argument to the method 🤔 Having `verify_and_process` return a "standardised" OpenID was maybe not a great choice and could be dropped when we get to 1.0.0.

For now, I am actually considering adding another method to the flow that would allow the user to get the response and ignore converting the OpenID.

**Comment by akimrx** [comment]
> I have to say I am not a fan of having return type differ based on an argument to the method 🤔 Having `verify_and_process` return a "standardised" OpenID was maybe not a great choice and could be dropped when we get to 1.0.0.
> 
> For now, I am actually considering adding another method to the flow that would allow the user to get the response and ignore converting the OpenID.

For my taste, standardization of the OpenID model is good. At least this gives at least some guarantees of somehow consistent data.

I think an additional method would be a good solution

**Comment by tomasvotava** [comment]
@akimrx I owe you an apology, I thought `overload` decorator was not available in 3.8, but it is there, so I prepared this PR based on your proposal #148

**Comment by tomasvotava** [comment]
Superseded by #148

**Pull request closed without merging**
