### PR TITLE
pydantic.EmailStr integration

### PR DESCRIPTION
**Pull request by parfeniukink**
Since the pydantic is used for validation. It is better to work with all its types.
This PR includes small changes regarding upgrading pydantic dependency and also sorting all dependencies alphabetically.

### CODE REVIEW

**Comment by tomasvotava** [comment]
I agree, do we even need to keep `str` in the union as well?

**Comment by parfeniukink** [comment]
> I agree, do we even need to keep `str` in the union as well?

I would keep it, especially for backward capability

**Comment by parfeniukink** [comment]
> I think that actually defies the purpose of using the `EmailStr` in the first place. You say we only accept valid e-mail addresses and any string, why include the subset with superset? Am I missing anything? 🤔

Nope, I am fine with removing a regular str here but it means that people can use the fastapi-sso only with pydantic data models. Providing the `str` as a secondary type parameter allows people with other Data modeling tools to work with fastapi-sso.

BTW, I am fine leaving only the `EmailStr` but we have to increase the Major version in that case, so we can be sure that it is not broken for people who have auto-updates.

What do you think?

**Comment by tomasvotava** [comment]
I'd like to avoid raising major to 1 for as long as possible, I am not yet quite satisfied with the interface, my understanding of OIDC and OAuth wasn't deep enough to design this well from the begining, tbh. There's a disclaimer in the README that the API is experimental, I know it sounds alibistic, it maybe even is :smile:

If you think there may be situations where any of the supported SSO's try to put something that's not an e-mail into the `email` field, let's keep your original way and allow `str` until we release 1.0.0 and only allow EmailStr.

What do you say?

**Comment by parfeniukink** [comment]
@tomasvotava Please have a look on this :)

**Review by tomasvotava — APPROVED** [review]
Looks good to me, thanks :)

**Pull request merged**
