### PR TITLE
Fix GitHub private email

### PR DESCRIPTION
**Pull request by Cereal84**
This PR resolves issue #54.

### Problem
If the user sets the email as private then when we call 'userinfo_endpoint' the data does not contain the email address.

### Solution
We need to use a new endpoint "https://api.github.com/user/emails" which returns a list of user's emails.

### Code
I added the new endpoint to the DiscoveryDocument under the key 'emails_endpoint', this key is defined as NotRequired for 2 reasons:

- other SSO classes do not need that
- mypy returns an error if this key is not used by the other classes.

GithubSSO class implement __get_extra_data()__ method in order to retrieve the email via __emails_endpoint__ if the __userinfo_endpoint__ not contains it.

The __get_extra_data()__ is called by the SSOBase class and each derived class can implement it if its needed.

### CODE REVIEW

**Comment by Cereal84** [comment]
I don't understad the Check error:


`
Run orgoro/coverage@v3.1
  with:
    coverageFile: coverage.xml
    token: ***
    thresholdAll: 0
    thresholdNew: 0
    thresholdModified: 0
  env:
    POETRY_VIRTUALENVS_CREATE: false
    coverage_json: {}
    pythonLocation: /opt/hostedtoolcache/Python/3.9.18/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.18/x64/lib
comparing commits: base b6feebf0e88606b617da76b130aeb94fb21484f1 <> head 76dd4fab688d1faf3c69b244c1f6bce1e719647e
git new files: [] modified files: ["docs/sso/base.html","docs/sso/facebook.html","docs/sso/fitbit.html","docs/sso/github.html","docs/sso/gitlab.html","docs/sso/google.html","docs/sso/kakao.html","docs/sso/microsoft.html","docs/sso/naver.html","docs/sso/spotify.html","examples/gitlab.py","fastapi_sso/sso/base.py","fastapi_sso/sso/github.py","pyproject.toml"]
source: fastapi_sso
Results
  Average coverage 89% ✅
  No covered new files in this PR 
  Modified files coverage ✅
HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/orgoro/coverage/v3.1/webpack:/typescript-action/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
`

**Comment by tomasvotava** [comment]
Hi @Cereal84 and thanks for the PR! 🙏 

Do not sweat it over the failed coverage, that's just a bot commenting on the PR regarding the current test coverage, I don't think we need that.

I took a look at the code and it's a little sad that feature like this requires so much code, I am sorry about that. I understand that making `openid_from_response` into a classmethod may have introduced some problems.

The only think I don't like very much is making the `email_endpoint` part of the `DiscoveryDocument`. I don't think that's something any of the other SSO implementations will want, and also there may be lots of other provider-specific endpoints in the future and we don't want the DiscoveryDocument to get any more complicated, it's only a typeddict after all.

Could you please rework ita little so that the email endpoint is part of only the `GithubSSO`?

If you don't have the time I can always take it from here, but it's a nice contribution that I don't want to take from you.

**Comment by Cereal84** [comment]
Hi @tomasvotava,

thank you for the message, I really appreciate it.

I'll move __email_endpoints__ from __SSOBase__ class to __GithubSSO__ class.

If you have other comments please write it :)

**Comment by Cereal84** [comment]
@tomasvotava: Let me know what do you think about the solution.

**Comment by tomasvotava** [comment]
It seems very nice now, thanks a lot!

I made the failing steps of the workflow optional and created #56 to make this work better.
I should have probably created a new PR and then ask you to rebase, but I wanted to save you the work.

Saying that, I am used to be squashing commits on PR, but this would mark the whole fix look like my commit instead 🤦 I'll try to squash locally to keep your work attributed and then force push. If I am not able to do that, I'll simply forget about my squash policy this time, because that's my oopsie after all :smile:

**Comment by tomasvotava** [comment]
Also, everything would have been much easier in `openid_from_response` wasn't a classmethod. What do you think? Should we turn it to a method instead? I don't believe there are many use-cases when you get the payload somewhere else and want to create the `OpenID` instance.

**Comment by tomasvotava** [comment]
@Cereal84 sorry, this is harder then I first thought, there are lots of old commits that were out of sync with the master, am I right? Is this branch you are requesting to pull rather old?

**Comment by tomasvotava** [comment]
closes #51

**Comment by Cereal84** [comment]
@tomasvotava probably something goes wrong on my rebase.
I'll try to sync with the master and then rewrite the fix. For now, I close this PR.

**Comment by tomasvotava** [comment]
@Cereal84 I've given it a thought and I'll change `openid_from_response` into a instance method. That will make `get_extra_data` obsolete, all you'll have to do is change the GithubSSO's `openid_from_response`, I'll try to do it today ASAP. Thanks again a lot, we'll get there, I just want to keep the code as clean as possible.

**Comment by Cereal84** [comment]
> @Cereal84 I've given it a thought and I'll change `openid_from_response` into a instance method. That will make `get_extra_data` obsolete, all you'll have to do is change the GithubSSO's `openid_from_response`, I'll try to do it today ASAP. Thanks again a lot, we'll get there, I just want to keep the code as clean as possible.

There is no rush, take your time.
I agree with let the code cleaner as we can.

Meanwhile I'll resync my code base.

**Pull request closed without merging**
